version: '3.4'

x-restart-policy: &restart_policy
  restart: 'no'

networks:
  main:

volumes:
  postgres_backup: {}
  postgres_data: {}

services:
  django:
    <<: *restart_policy
    container_name: django
    build:
      context: .
      dockerfile: docker_compose/django/Dockerfile
      args:
        ENVIRONMENT: production
    command: 'sh -c "wait-for-it postgres:5432 && /start"'
    depends_on:
      - postgres
    env_file: .env
    image: django-image
    hostname: django
    networks:
      - main
    volumes:
      - './media/:/app/media/'

  postgres:
    <<: *restart_policy
    container_name: postgres
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    hostname: postgres
    image: 'postgres:12'
    networks:
      - main
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - 'postgres_backup:/backups'

  vuejs:
    <<: *restart_policy
    container_name: vuejs
    build:
      context: frontend
      dockerfile: docker_compose/vuejs/Dockerfile
      args:
        - ENVIRONMENT=production
        - VUE_APP_ROOT_API
        - VUE_APP_SITE_URL
        - VUE_APP_SITE_NAME
        - VUE_APP_PHONE_NUMBER
    env_file: .env
    hostname: vuejs
    networks:
      - main
