version: '3.4'

x-restart-policy: &restart_policy
  restart: unless-stopped

volumes:
  redis_data: {}
  static: {}

services:
  certbot:
    <<: *restart_policy
    image: certbot/certbot
    volumes:
      - './data/ssl/conf:/etc/letsencrypt'
      - './data/ssl/www:/var/www/certbot'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    command: "wait-for-it django:5000 -- /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
