version: '3.4'

x-restart-policy: &restart_policy
  restart: 'no'

networks:
  main:

volumes:
  postgres_backup: {}
  postgres_data: {}

services:
  django:
    <<: *restart_policy
    container_name: django
    build:
      context: .
      dockerfile: docker_compose/django/Dockerfile
      args:
        ENVIRONMENT: production
    command: 'wait-for-it postgres:5432 -- /start.sh'
    depends_on:
      - postgres
    env_file: .env
    image: yakim/chubbyfolio:latest
    hostname: django
    networks:
      - main
    volumes:
      - './public/:/app/public/'

  postgres:
    <<: *restart_policy
    container_name: postgres
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    hostname: postgres
    image: 'postgres:12'
    networks:
      - main
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - 'postgres_backup:/backups'

#  vuejs:
#    restart: 'no'
#    image: chubbyfolio-frontend
#    build:
#      context: .
#      dockerfile: docker_compose/vuejs/Dockerfile
#      args:
#        - ENVIRONMENT=production
