version: '3.4'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  django:
    <<: *restart_policy
    environment:
      - DJANGO_SETTINGS_MODULE=chubbyfolio.settings.production
      - SECRET_KEY
    build:
      args:
        ENVIRONMENT: production
    volumes:
      - './public:/app/public/'

  nginx:
    <<: *restart_policy
    container_name: nginx
    build:
      context: .
      dockerfile: docker_compose/nginx/Dockerfile
      args:
        - CHUBBYFOLIO_DOMAIN
    command: 'wait-for-it django:5000 -- nginx -g "daemon off;"'
    depends_on:
      - django
    networks:
      - main
    volumes:
      - './public/:/usr/share/nginx/html:ro'
      - './data/ssl/conf:/etc/ssl'
      - './data/ssl/www:/var/www/certbot'
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  postgres:
    <<: *restart_policy
