version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    container_name: postgres_server
    build: ./docker_compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env.staging.local

  django:
    container_name: django_server
    build:
      context: .
      dockerfile: ./docker_compose/django/production/Dockerfile
    user: django
    depends_on:
      - postgres
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
    command: /start.sh
    env_file: .env.staging.local

  vuejs:
    container_name: vuejs_server
    build:
      dockerfile: ./docker_compose/vuejs/production/Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/dist/:/home/node/app/dist
    env_file: ./frontend/.env.staging.local

  nginx:
    container_name: nginx_server
    build:
      context: ./docker_compose/nginx/staging
      args:
        - CHUBBYFOLIO_DOMAIN
    environment:
      - CHUBBYFOLIO_DOMAIN
    depends_on:
      - django
      - vuejs
    volumes:
      - ./static/:/static:ro
      - ./media/:/media:ro
      - ./frontend/dist/:/usr/share/nginx/html:ro
      - ./data/certs:/etc/nginx/certs:ro
    ports:
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
