# Generated by Django 2.1.3 on 2018-12-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20181212_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
