# Generated by Django 2.1.3 on 2018-12-08 16:06

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import photosets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=photosets.models.upload_photosets_to, verbose_name='изображение')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photoset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=photosets.models.upload_previews_to, verbose_name='превью для главной')),
                ('show_on_mainpage', models.BooleanField(default=False, verbose_name='показывать на главной')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'фотосет',
                'verbose_name_plural': 'фотосеты',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photoset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photosets.Photoset', verbose_name='фотосет'),
        ),
    ]
