# Generated by Django 2.2.5 on 2019-09-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosets', '0006_photo_is_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
