# Generated by Django 2.1.3 on 2018-12-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainScreenPhotos',
            new_name='MainScreenPhoto',
        ),
    ]
