# Generated by Django 2.1.3 on 2018-12-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_settings', '0003_mainscreenphoto_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainscreenphoto',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, unique=True, verbose_name='очередность'),
        ),
    ]
