# Generated by Django 2.1.3 on 2018-12-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_settings', '0004_auto_20181210_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainscreenphoto',
            options={'ordering': ['priority', 'date'], 'verbose_name': 'фотография на главной', 'verbose_name_plural': 'фотографии на главной'},
        ),
    ]
