# Generated by Django 2.1.3 on 2018-12-05 00:38

from django.db import migrations, models
import django.db.models.deletion
import photosets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to=photosets.models.upload_to, verbose_name='изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Photoset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'фотосет',
                'verbose_name_plural': 'фотосеты',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photoset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photosets.Photoset', verbose_name='фотосет'),
        ),
    ]
