# Generated by Django 2.1.3 on 2018-12-24 19:04

from django.db import migrations
import easy_thumbnails.fields
import photosets.models


class Migration(migrations.Migration):

    dependencies = [
        ('photosets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoset',
            name='preview',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=photosets.models.upload_previews_to, verbose_name='превью для главной'),
        ),
    ]
