# Generated by Django 2.2.5 on 2019-09-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosets', '0002_auto_20181224_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
