# Generated by Django 2.2.5 on 2019-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosets', '0005_auto_20190916_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Обложка'),
        ),
    ]
