name: build

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Linting
        run: |
          make lint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: cp env.ci.example .env
    - name: Run tests
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm django pytest --cov
